//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raumschach_Chess {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Raumschach_Chess.res", typeof(res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bishop.
        /// </summary>
        internal static string BishopPath {
            get {
                return ResourceManager.GetString("BishopPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0-1 Black Wins .
        /// </summary>
        internal static string BlackWins {
            get {
                return ResourceManager.GetString("BlackWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer.
        /// </summary>
        internal static string Computer {
            get {
                return ResourceManager.GetString("Computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0-0 Draw By 50 Moves Rule.
        /// </summary>
        internal static string DrawByFifty {
            get {
                return ResourceManager.GetString("DrawByFifty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0-0 Draw By Stalemate.
        /// </summary>
        internal static string DrawByStalemate {
            get {
                return ResourceManager.GetString("DrawByStalemate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input is not valid.
        /// </summary>
        internal static string ErrorNotValidInput {
            get {
                return ResourceManager.GetString("ErrorNotValidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mysavedgames.txt.
        /// </summary>
        internal static string FileWithSaves {
            get {
                return ResourceManager.GetString("FileWithSaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human.
        /// </summary>
        internal static string Human {
            get {
                return ResourceManager.GetString("Human", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to king.
        /// </summary>
        internal static string KingPath {
            get {
                return ResourceManager.GetString("KingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to knight.
        /// </summary>
        internal static string KnightPath {
            get {
                return ResourceManager.GetString("KnightPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Models.
        /// </summary>
        internal static string ModelPath {
            get {
                return ResourceManager.GetString("ModelPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pawn.
        /// </summary>
        internal static string PawnPath {
            get {
                return ResourceManager.GetString("PawnPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to queen.
        /// </summary>
        internal static string QueenPath {
            get {
                return ResourceManager.GetString("QueenPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rook.
        /// </summary>
        internal static string RookPath {
            get {
                return ResourceManager.GetString("RookPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unicorn.
        /// </summary>
        internal static string UnicornPath {
            get {
                return ResourceManager.GetString("UnicornPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-0 White Wins.
        /// </summary>
        internal static string WhiteWins {
            get {
                return ResourceManager.GetString("WhiteWins", resourceCulture);
            }
        }
    }
}
