#define BOOL			int
#define TRUE			1
#define FALSE			0

#define LIGHT			0
#define DARK			1

#define PAWN			0
#define KNIGHT			1
#define UNICORN         2 
#define BISHOP			3
#define ROOK			4
#define QUEEN			5
#define KING			6

#define EMPTY           7

#define BOARD_X_DIMENSION 5 //rows
#define BOARD_Y_DIMENSION 5 //planes
#define BOARD_Z_DIMENSION 5 //columns

#define LIGHT_PAWN_AHEAD_LEFT       -BOARD_X_DIMENSION-1
#define LIGHT_PAWN_AHEAD_RIGHT      -BOARD_X_DIMENSION+1
#define LIGHT_PAWN_UP_LEFT  -(BOARD_X_DIMENSION * BOARD_X_DIMENSION )-1
#define LIGHT_PAWN_UP_RIGHT -(BOARD_X_DIMENSION * BOARD_X_DIMENSION )+1

#define DARK_PAWN_BACK_LEFT         BOARD_X_DIMENSION-1
#define DARK_PAWN_BACK_RIGHT        BOARD_X_DIMENSION+1
#define DARK_PAWN_UP_BACK_LEFT      BOARD_X_DIMENSION * BOARD_X_DIMENSION + BOARD_X_DIMENSION-1
#define DARK_PAWN_UP_BACK_RIGHT     BOARD_X_DIMENSION * BOARD_X_DIMENSION + BOARD_X_DIMENSION+1

#define LIGHT_PAWN_DOWN              -BOARD_X_DIMENSION * BOARD_X_DIMENSION
#define DARK_PAWN_UP                BOARD_X_DIMENSION * BOARD_X_DIMENSION


